/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EntraRouteImport } from './routes/entra'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedDocenteRouteImport } from './routes/_authenticated/docente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EntraRoute = EntraRouteImport.update({
  id: '/entra',
  path: '/entra',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocenteRoute = AuthenticatedDocenteRouteImport.update({
  id: '/docente',
  path: '/docente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entra': typeof EntraRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/docente': typeof AuthenticatedDocenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entra': typeof EntraRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/docente': typeof AuthenticatedDocenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/entra': typeof EntraRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/docente': typeof AuthenticatedDocenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/entra' | '/diario' | '/docente'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/entra' | '/diario' | '/docente'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/entra'
    | '/_authenticated/diario'
    | '/_authenticated/docente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EntraRoute: typeof EntraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entra': {
      id: '/entra'
      path: '/entra'
      fullPath: '/entra'
      preLoaderRoute: typeof EntraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docente': {
      id: '/_authenticated/docente'
      path: '/docente'
      fullPath: '/docente'
      preLoaderRoute: typeof AuthenticatedDocenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedDocenteRoute: typeof AuthenticatedDocenteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedDocenteRoute: AuthenticatedDocenteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EntraRoute: EntraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
